#!/usr/bin/env bash
# Stop and remove the trio containers.
#
# Usage:
#   ./stop-all.sh              # stop containers, keep volumes (data preserved)
#   ./stop-all.sh --purge      # stop containers + delete volumes + delete network (full cleanup)

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_lib.sh
source "$SCRIPT_DIR/_lib.sh"

PURGE=0
if [[ "${1:-}" == "--purge" ]]; then
  PURGE=1
fi

# Allow running even when .env is absent (fall back to default volume names)
if [[ -f "$ENV_FILE" ]]; then
  set -a; source "$ENV_FILE"; set +a
fi
MEMORY_CORE_VOLUME="${MEMORY_CORE_VOLUME:-tdai-memory-core-data}"
PANEL_VOLUME="${PANEL_VOLUME:-tdai-panel-data}"

for c in tdai-proxy tdai-memory-hub tdai-memory-core; do
  if $DOCKER ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "$c"; then
    info "Stopping and removing $c"
    $DOCKER rm -f "$c" >/dev/null
  else
    info "$c not running, skipping"
  fi
done

if (( PURGE == 1 )); then
  warn "--purge enabled: deleting volumes + network + admin key file"
  for v in "$MEMORY_CORE_VOLUME" "$PANEL_VOLUME"; do
    if $DOCKER volume inspect "$v" >/dev/null 2>&1; then
      $DOCKER volume rm "$v" >/dev/null && ok "Deleted volume $v" || warn "Failed to delete volume $v"
    fi
  done
  if $DOCKER network inspect tdai-memory-stack >/dev/null 2>&1; then
    $DOCKER network rm tdai-memory-stack >/dev/null && ok "Deleted network tdai-memory-stack" || true
  fi
  # admin key is strongly bound to the volume; purging the volume must also clear the key,
  # otherwise the next start reads an old key against a fresh volume and auth verification fails.
  ADMIN_KEY_FILE="${MEMORY_CORE_ADMIN_KEY_FILE:-$SCRIPT_DIR/.admin-key}"
  if [[ -f "$ADMIN_KEY_FILE" ]]; then
    rm -f "$ADMIN_KEY_FILE" && ok "Deleted admin key file $ADMIN_KEY_FILE"
  fi
  # Also clear the config generated by proxy / memory-core
  PROXY_CFG_DIR="${PROXY_CONFIG_DIR:-$SCRIPT_DIR/.proxy-config}"
  if [[ -d "$PROXY_CFG_DIR" ]]; then
    rm -rf "$PROXY_CFG_DIR" && ok "Deleted proxy config dir $PROXY_CFG_DIR"
  fi
  CORE_CFG_DIR="${MEMORY_CORE_CONFIG_DIR:-$SCRIPT_DIR/.memory-core-config}"
  if [[ -d "$CORE_CFG_DIR" ]]; then
    rm -rf "$CORE_CFG_DIR" && ok "Deleted memory-core config dir $CORE_CFG_DIR"
  fi
fi

ok "Done."
